---
title: "Classic results with rescomp"
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{classic-results}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette reproduces classic results from the literature with `rescomp`.

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rescomp)
```

#### Huisman and Weissing (1990) Biodiversity of plankton by species oscillations and chaos. *Nature*.


```{r}
pars <- spec_rescomp(
  spnum = 6, 
  resnum = 3,
  funcresp = "type2",
  mumatrix = list(matrix(c(1, 1, 1, 
                           1, 1, 1, 
                           1, 1, 1, 
                           1, 1, 1, 
                           1, 1, 1,
                           1, 1, 1), 
                         nrow = 6, 
                         ncol = 3,
                         byrow = TRUE)),
  kmatrix = matrix(c(1.00, 0.30, 0.90,
                     0.90, 1.00, 0.30,
                     0.30, 0.90, 1.00,
                     1.04, 0.71, 0.46,
                     0.34, 1.02, 0.34,
                     0.77, 0.76, 1.07), 
                   nrow = 6, 
                   ncol = 3,
                   byrow = TRUE),
  qmatrix = matrix(c(0.04, 0.08, 0.14,
                     0.07, 0.08, 0.10,
                     0.04, 0.10, 0.10,
                     0.10, 0.10, 0.16,
                     0.03, 0.05, 0.06,
                     0.02, 0.17, 0.14), 
                   nrow = 6, 
                   ncol = 3,
                   byrow = TRUE),
  resspeed = 0.25,
  resconc = c(6, 10, 14),
  mort = 0.25,
  cinit = c(0.1 + 1/100, 0.1 + 2/100, 0.1 + 3/100, 0.1, 0.1, 0.1),
  essential = TRUE,
  totaltime = 15000, 
  introseq = c(0, 0, 0, 1000, 2000, 5000)
)
```
```{r}
plot_funcresp(pars)
```



```{r, cache = TRUE}
m1 <- sim_rescomp(pars)
```

```{r, fig.cap = "Reproduces Fig 1c from Huisman and Weissing (1990)."}
plot_rescomp(m1, resources = FALSE)
```

#### Grover (1990) Resource Competition in a Variable Environment: Phytoplankton Growing According to Monod's Model. *The American Naturalist*.
